version: '2.3'

services:
    #3°
    app:
        build: .
        container_name: app
        volumes:
            - .:/var/www
        networks:
            - app-network
        #Evita o erro ao carregar o volume do banco de dados
        depends_on:
            db:
                condition: service_healthy
    #1°
    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
    #5°
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network
        #Verifica se o banco de dados está pronto 
        healthcheck:
            test: ["CMD-SHELL", 'mysql -uroot --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
            interval: 10s
            timeout: 10s
            retries: 4

    #2°
    redis:
        image: redis:alpine
        expose:
            - 6379
        networks:
            - app-network
#4°           
networks:
    app-network:
        driver: bridge