version: '3'

services:
    #3°
    app:
        build: .
        container_name: app
        entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh find storage bootstrap/cache public -type f -exec chmod o+w {} find storage bootstrap/cache public -type d -exec chmod o+wx {} chmod o-w public/index.php
        environment: 
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        volumes:
            - .:/var/www
        networks:
            - app-network
        #Evita o erro ao carregar o volume do banco de dados
        depends_on:
            - db
            - redis

    #1°
    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app
    #5°
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network
        
    #2°
    redis:
        image: redis:alpine
        expose:
            - 6379
        networks:
            - app-network
#4°           
networks:
    app-network:
        driver: bridge